events {}

http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://gateway-service:8087/;
    }

    location /auth/ {
      proxy_pass http://session-service:8081/;
    }
  }
}
